### ISSUE TITLE
Dashboard 添加呈现主观评价指标对比的复合型图表

### ISSUE THREAD

**Issue by nightire** [choice-form/bts-reports#10]
**主观评价指标（criterions）** 是我临时起的名字，如有正式名称烦请指正。

主观评价指标来自于问卷的一道嵌入式级联选择题（分二级）

其中一级和二级指标分别是：

- 外观设计
  - 时尚动感
  - 大气沉稳
  - 豪华高档
  - 与众不同
  - 科技氛围
  - 硬朗霸气
  - 人性化设计
- 内饰感观
  - 与众不同
  - 科技氛围
  - 硬朗霸气
  - 精致考究
  - 配色舒服
  - 人性化设计
- 产品品质
  - 做工精良
  - 用料上乘
  - 皮实耐用
  - 故障率低
  - 车身坚固
- 安全性
  - 车身坚固
  - 安全配置
  - 安全技术
  - 驾驶视野
  - 车辆尺寸大
  - 碰撞星级
  - 全路况能力
  - 四驱技术
- 驾驶性能
  - 全路况能力
  - 四驱技术
  - 操控精准
  - 动力强劲
  - 底盘扎实
  - 驾驶平顺
- 乘坐体验
  - 驾驶平顺
  - 空间宽敞
  - 座椅舒适
  - 静音低噪
  - 减震效果
  - 新车异味少
  - 娱乐功能
- 技术先进
  - 安全技术
  - 四驱技术
  - 发动机技术
  - 底盘技术
  - 变速箱技术
  - 自动驾驶
  - 网联技术
  - 语音控制
- 节油高效
  - 自动驾驶
  - 网联技术
  - 语音控制
  - 节能省油
  - 发动机效率
  - 车身轻量化
- 日常实用
  - 节能省油
  - 载物空间大
  - 装载人数多
  - 车小灵活
  - 多种用途
  - 储物设计
  - 科技配置
  - 灵活空间
  - 适合家庭
- 贴心方便
  - 自动驾驶
  - 网联技术
  - 语音控制
  - 车小灵活
  - 储物设计
  - 科技配置
  - 灵活空间
  - 操作便利
  - 人性化设计
  - 智能交互
- 智能互联
  - 自动驾驶
  - 网联技术
  - 语音控制
  - 科技配置
  - 操作便利
  - 人性化设计
  - 智能交互
  - 在线服务
- 健康环保
  - 节能省油
  - 尾气排放低
  - 新车异味少
  - 空气过滤好
- 性价比高
  - 节能省油
  - 价格实惠
  - 优惠力度
  - 配置丰富
  - 保值率高
  - 维保便宜
  - 省购置税
  - 质保时间
- 服务优质
  - 质保时间
  - 服务环境
  - 服务人员
  - 服务速度
  - 网点覆盖
  - 配套服务
  - 金融服务
  - 在线服务

注意：
1. 一级和二级之间是互为 1..n 的关系，也就是说二级指标可能从属于多个一级指标
2. 每一个指标都需要实现 i18n

综上，建议为所有指标建模，并至少拥有 `level` 和 `code` 两个字段。

Dashboard 将使用 **下钻式柱状图（drill down column）** 和 **折线图** 结合的方式来呈现，其中下钻式柱状图用来显示通用三品牌（任选其一）作为对比的基准，折线图则显示对比品牌（即排除通用三品牌之后的任一品牌），可以显示多个品牌（对应多条折线）。其他查询参数都是共享的（以确保对比数据的各纬度都相同）。

下钻图的作用在于可以交互式的显示两级指标，初始状态显示的是一级指标（每个指标对应一个柱或一个线上的点），点击任一一个指标的图形，图表会刷新并显示从属于该指标的二级指标（折线对应一起下钻），再次点击回返一级指标图表。

因此建议对应 API Response 的草案如下：

``` typescript
/**
 * `GET /api/criterions?brand_ids=1,2,3,4,5&OTHER_PARAMS`
 * 1. 是 `brand_ids` 还是 `subject_ids` 由 @陈璋 决定，但最好是 `brand_ids`，因为这样我更容易区分哪些是通用三品牌（id 确定），如果是 `subject_ids`，那我还需要通过 `subject.brand_id` 去查找和筛选哪些是通用三品牌。
 * 2. `OTHER_PARAMS` 应该是和 `funnels` API 一致（暂时想不到需要不同的地方）
 */
[
  {
    brand_id: <number>,
    criterions: [
      {
        id: <number>,
        code: <string>,
        count: <number>,
        level: <number>,
        children: [
          {
            id: <number>,
            code: <string>,
            count: <number>,
            level: <number>
          },
          ...
        ]
      },
      ...
    ]
  },
  ...
]
```

**Comment by darkbaby123** [comment]
我有几个问题：

1. API 定义方面，如果还是一次获取某个 level 或者 project 下的所有数据，应该可以不需要 subject_ids 或 brand_ids ？
1. criterions 本身应该没有 level 吧？它们的 level 本质上还是来自于 brand ？但如果你说的 level 是 criterions 本身是第一层还是第二层，那就没问题了。

另外 criterions 的 count 感觉不太合理，我举个例子，假如有个样本对某品牌贡献了如下数据（已选中的项）：

- 外观设计
  - 时尚动感
  - 大气沉稳
  - 豪华高档
- 内饰感观
  - 与众不同

这里的选项有个特点，就是每个选项不会被选择两次，这就导致 payload 里第二层的 `count` 始终是 0 ，第一层的 `count` 始终是第二层的数量总和，因此我感觉 `count` 的意义不大了。它本质上不是 criterions 的属性，而是它上层的某项统计数据。

**Comment by nightire** [comment]
1. 也可以这么做，即：一次性获取到所有 subjects 的数据，然后在客户端进行挑拣。之所以会要 ids 的原因是这个图表并不会一次性显示所有的 subjects，确定一定会显示的只有通用三品牌其中之一（在同一时刻）以及（可选的）多个用于对比的品牌。如果一次性获取所有数据我认为也可以，在客户端做挑拣也行。

2. 这个 `level` 不是档次，而是 criterions 的级别。

3. 你说的不合理是单个样本对于某品牌的贡献，这当然不需要 count，但我说的是图表需要的聚合数据，也就是所有符合条件的样本对于该品牌在指定 criterion 上的贡献总计。不然的话，所有的二级 criterion 计数都是 1 了，那图表还对比什么啊。

**Comment by darkbaby123** [comment]
明白了，1 就一次性获取全部数据吧，其他按你说的来。

`code` 该填什么，中文名称？

**Comment by nightire** [comment]
就中文吧……这么多英文我懒得编🙀
