### ISSUE TITLE
dashboard 中漏斗结果与筛选器不匹配的问题

### ISSUE THREAD

**Issue by darkbaby123** [choice-form/bts-reports#14]
俊波反映过这个问题，在 dashboard 中修改所在市场或筛选器等地方导致页面刷新时，有可能看到计算结果和 UI 状态不一致。再改一下又好了。

我猜测是因为在修改筛选器后仍在 loading 的时候继续改成其他值，会导致多次未结束的 funnels 请求，因为网络环境的不确定行，可能导致前一个请求后到，最终 UI 渲染的是第一次修改筛选器的结果。

**Comment by nightire** [comment]
@darkbaby123 你的猜测大致正确，不过这个问题解决起来并不容易。由于时间的关系，本项目里绝大多数 Ajax 请求都是没有做并发控制的，特别是在做 dashboard 第一版及之前，都是普普通通的 `fetch` 请求而已。

直到 dashboard 第一版结束之后，因为我观察到 dashboard 的异步并发与状态管控的复杂性，比方说，如果只是一个两个请求，你大概可以用自己管理的 `loading` 状态来控制，可如果一个视图可能会同时并发 n 个异步请求，那么 n 个 loading 管理起来就太复杂了。

鉴于此，我已经打算引入 ember-concurrency 来辅助并发管理了，特别是[文档这部分](http://ember-concurrency.com/docs/task-concurrency)的 `enqueue` 及 `drop`，正是解决这个问题的对症良药。但问题是下周二之前恐怕是来不及做这个重构的，所以涉及到请求的地方都需要重构，时间太紧。

一个可行的临时方案是扩大 loading 元素的覆盖面积，让它们把 market 和 filters 遮挡起来，这就杜绝了用户作出大量异步并发的可能性，等 ember-concurrency 重构好后再逐步放开。

@oo6 同样的问题其实也会在 os-dashboard 遇到的，只不过不会像 bts-reports 这么显著，ember-concurrency 是好东西，我在 collectors 的统计图表那里已经用了，有时间可以学习一下充实武器库。

**Comment by darkbaby123** [comment]
@nightire 明白了。这个最后处理吧。如果你还有空余时间做临时方案就弄一下。

**Comment by nightire** [comment]
@darkbaby123 已用临时方案解决，暂时关闭这个 issue，以后要重构再开启。
